# Generated by Django 5.0.6 on 2024-06-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="qna",
            fields=[
                ("qna_id", models.IntegerField(primary_key=True, serialize=False)),
                ("member_id", models.CharField(max_length=30)),
                ("qna_date", models.DateTimeField()),
                ("qna_type", models.IntegerField()),
                ("qna_title", models.CharField(max_length=100)),
                ("qna_content", models.CharField(max_length=1000)),
                ("qna_state", models.CharField(max_length=40)),
            ],
        ),
    ]
