# Generated by Django 5.0.6 on 2024-06-26 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="qna",
            fields=[
                ("qna_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_id", models.CharField(max_length=30)),
                ("qna_date", models.DateField(default=django.utils.timezone.now)),
                ("qna_type", models.IntegerField()),
                ("qna_title", models.CharField(max_length=100)),
                ("qna_content", models.CharField(max_length=1000)),
                ("qna_state", models.CharField(default="답변중", max_length=40)),
            ],
        ),
    ]
